### ISSUE TITLE
The callback decrypt() exists in module aescrypto, but only one callback may be registered to a function in a native module.

### ISSUE THREAD

**Issue by luolin2611** [rocwangv/react-native-aes-kit#2]
Hi，This plug-in I use on the Android phone, encryption and decryption no problem. However, the following error occurred on the IOS phone.
![image](https://user-images.githubusercontent.com/17327008/40903692-da22632a-680a-11e8-8452-ca547495ee8f.png)
The callback decrypt() exists in module aescrypto, but only one callback may be registered to a function in a native module.

**Comment by rocwong-cn** [comment]
Can you provide your RN version ?

**Comment by luolin2611** [comment]
hello,Thank you for your answer. My environment is as follows.
react-native-cli:     2.0.1
react-native:      0.50.3
node       v8.11.1
npm        5.6.0
yarn        1.6.0

**Comment by rocwong-cn** [comment]
I tried with RN version 0.50.3 and nothing error.
 [Here](https://github.com/rocwangv/AESExample) is my code.
